# Exploratory Data Analysis

In [2]:
import numpy as np
import pandas as pd

In [3]:
tst = pd.read_sas("TST_L.xpt")
biochem = pd.read_sas("BIOPRO_L.xpt")

In [9]:
tst.head()

,SEQN,WTPH2YR,LBX17H,LBD17HSI,LBD17HLC,LBXAND,LBDANDSI,LBDANDLC,LBXAMH,LBDAMHSI,...,LBXLUH,LBDLUHLC,LBXPG4,LBDPG4SI,LBDPG4LC,LBXSHBG,LBDSHGLC,LBXTST,LBDTSTSI,LBDTSTLC
0,130378.0,5.604213e+04,158.0,4.79,5.397605e-79,50.6,1.77,5.397605e-79,3.37,24.06,...,3.42,5.397605e-79,6.37,0.203,5.397605e-79,23.94,5.397605e-79,668.0,23.200,5.397605e-79
1,130379.0,3.743571e+04,76.2,2.31,5.397605e-79,79.5,2.77,5.397605e-79,2.99,21.35,...,2.96,5.397605e-79,4.04,0.128,5.397605e-79,57.46,5.397605e-79,437.0,15.200,5.397605e-79
2,130380.0,8.532884e+04,51.3,1.55,5.397605e-79,71.9,2.51,5.397605e-79,0.31,2.21,...,2.67,5.397605e-79,565.00,18.000,5.397605e-79,52.01,5.397605e-79,13.8,0.479,5.397605e-79
3,130381.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,130386.0,4.452621e+04,81.8,2.48,5.397605e-79,63.4,2.21,5.397605e-79,5.90,42.13,...,4.51,5.397605e-79,3.43,0.109,5.397605e-79,40.83,5.397605e-79,473.0,16.400,5.397605e-79

In [10]:
biochem.head()

,SEQN,WTPH2YR,LBXSATSI,LBXSAL,LBDSALSI,LBXSAPSI,LBXSASSI,LBXSC3SI,LBXSBU,LBDSBUSI,...,LBXSCA,LBDSCASI,LBXSCH,LBDSCHSI,LBXSTP,LBDSTPSI,LBXSTR,LBDSTRSI,LBXSUA,LBDSUASI
0,130378.0,56042.129410,39.0,4.3,43.0,91.0,25.0,24.0,11.0,3.9,...,9.6,2.4,266.0,6.89,7.5,75.0,153.0,1.73,5.1,303.3
1,130379.0,37435.705647,17.0,3.9,39.0,64.0,20.0,25.0,24.0,8.6,...,9.4,2.4,217.0,5.62,7.3,73.0,88.0,0.99,8.5,505.6
2,130380.0,85328.844519,13.0,3.7,37.0,78.0,15.0,25.0,10.0,3.6,...,9.4,2.4,183.0,4.74,7.6,76.0,375.0,4.24,4.4,261.7
3,130386.0,44526.214135,34.0,4.3,43.0,54.0,20.0,21.0,17.0,6.1,...,9.5,2.4,185.0,4.79,6.9,69.0,140.0,1.58,6.0,356.9
4,130387.0,22746.296353,12.0,3.7,37.0,116.0,13.0,24.0,15.0,5.4,...,9.3,2.3,203.0,5.26,6.7,67.0,111.0,1.25,6.2,368.8